on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - master
      - develop
      - upgrade-library
    paths-ignore:
      - 'README.*'
  pull_request:
      types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  run_tests:
    name: Create Conda Env & Run pytest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: üì• Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Disabling shallow clone is recommended for improving relevancy of reporting

      - name: üü¢ Create Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pycallgraph
          environment-file: dev-env.yaml
          auto-activate-base: false

      - name: üêç Python Setup
        run: python setup.py install

      - name: üßê Run pytest
        run: pytest --cov-report xml:coverage.xml

      - name: ‚òÅ SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
